
### eth_getTransactionByHash
POST https://mainnet.infura.io/1UoO4I
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionByHash",
    "params":["0x802a072a303a1bb19a20065a262526f2cfda0d1ea16eeb3db6500d9d06f65963"],
    "id":67
}

### eth_getTransactionByHash
POST http://123.206.29.15:8540
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionByHash",
    "params":["0xb66f549b119ebadfb1a48e6d6ad99ad7210673e6a07422c65a379fa388779de2"],
    "id":67
}

### eth_getTransactionReceipt
POST https://mainnet.infura.io/1UoO4I
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionReceipt",
    "params":["0x802a072a303a1bb19a20065a262526f2cfda0d1ea16eeb3db6500d9d06f65963"],
    "id":67
}

### eth_getTransactionReceipt
POST http://123.206.29.15:8540
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_getTransactionReceipt",
    "params":["0xb66f549b119ebadfb1a48e6d6ad99ad7210673e6a07422c65a379fa388779de2"],
    "id":67
}


